Story1 display collection
smccsw/collectors-app pull request #3
Opened 2021-08-04 13:13 UTC by smccsw

2021-08-04 15:33 UTC, norayna commented on index.php
> +
just one blank line here (and anywhere) would be better

2021-08-04 15:38 UTC, norayna commented on functions.php
> +        if (!is_string($team['teamName']) || !is_string($team['poles']) || !is_string($team['wins']) || !is_string($team['podiums'])) {
this is checking that the values are all of the right type, which is good. however it is not checking whether all the keys are there.

i would say you should keep these checks in place and also add checks that the keys exist in the first place, for example an empty array might be given (no keys and values) and that would cause an error later in the program. so if you can add checks that the keys exist, that would be grand.

2021-08-04 15:52 UTC, norayna requested changes
little changes requested

2021-08-05 09:21 UTC, smccsw commented on functions.php
> +        if (!is_string($team['teamName']) || !is_string($team['poles']) || !is_string($team['wins']) || !is_string($team['podiums'])) {
Done, but a bit weird. Would like to revisit the issues I was having on this with you when we get a chance.

2021-08-05 12:58 UTC, norayna approved these changes

2021-08-05 12:59 UTC, merged